parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_PERSISTENT): 'false'
    env(DATABASE_SOCKET): ''
    env(DATABASE_USER): ''
    env(DATABASE_PASSWORD): ''
    env(DATABASE_NAME): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        persistent: '%env(bool:DATABASE_PERSISTENT)%'
        unix_socket: '%env(resolve:DATABASE_SOCKET)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        options:
            !php/const:PDO::ATTR_PERSISTENT: '%env(bool:DATABASE_PERSISTENT)%'
