sudo: required

language: jvm

jdk: openjdk9

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=awlodarkiewicz/devops:build-latest
    - HOST_PATH=/home/travis/build/adshares/aduser
    - BUILD_PATH=/build/aduser
    - BUILD_NAME=aduser_build
    - ADUSER_TRACKING_SECRET=NotVerySecret_Proxy
    - ADUSER_COOKIE_NAME=aduser_proxy_tid
    - ADUSER_EXPIRY_PERIOD=4w
    - ADUSER_MONGO_DB_PORT=27017
    - ADUSER_MONGO_DB_NAME=aduser_cache
    - ADUSER_LOG_CONFIG_FILE=$BUILD_PATH/config/log_config.json
    - ADUSER_PLUGINS_PATH=$BUILD_PATH/aduser/plugins
    - ADUSER_DATA_PATH=$BUILD_PATH/aduser/data
    - ADUSER_PORT=9000
    - ADUSER_DATA_PROVIDER=example

  matrix:
    - ADUSER_APP_ENV=dev

stages:
  - Test build, test code, test quality

before_script:
  # Enable aliases for non-interactive shells
  - shopt -s expand_aliases
  # Set alias - please note the missing quote you need to append.
  - alias in_docker='docker exec $BUILD_NAME /bin/bash -c "cd $BUILD_PATH && '
  # Set alias for cleanup
  - alias cleanup_docker='docker stop $BUILD_NAME && docker rm $BUILD_NAME'

jobs:
  include:
    # Python unit tests
    - stage: Test build, test code, test quality
      script:
        ## Setup test environment
        # Run docker container
        - docker pull $DOCKER_IMAGE
        - env | grep ADUSER > aduser.env
        - >
          docker run -d
          --mount type=bind,src=$HOST_PATH,dst=$BUILD_PATH
          -e PYTHONPATH=$BUILD_PATH
          -e TRAVIS=true
          -e PIPENV_VENV_IN_PROJECT=1
          --env-file aduser.env
          --name $BUILD_NAME
          $DOCKER_IMAGE
          sleep infinity

        # Run pre-build script
        - in_docker /bin/bash scripts/pre-build.sh"

        # Run build script
        - in_docker /bin/bash scripts/build.sh"

        - in_docker pipenv run install_geoip"

        - in_docker pipenv run tests"

        - in_docker pipenv run quality"

        - sonar-scanner

        # Cleanup
        - cleanup_docker

# After a build, send email notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure: "O7gaiki4jX++eADjMM/REPHPfCpgbQvmkcGPETsrQw8Pj8xNnNLE4OzOeoxIsNoZjLRMGnRVp600UrnJlEE1SqJkgjevyzJnCz0fc5SM66S8W3vpdgJofR5jm5E0Kk5omfxGehp38iiM9FtECRTuKd3zP9sk0pK07b1ROCWFxkAxxoU+7d49fiFwKz7ikPEXvyT6FhbZaSK6sRqk1WR5jrOBupZQUBbOXfGDkba3/Vq87gWe4VP22/lgdh+tpA1hZ+QJW2+IETjXxwiQ05E39vNWJXyi6pRL4qusJR+mH0yqTBY9CDVmd0B4m45gNo9FzaXMkxmdorIf7ypJw/WAe7NNQpL6QoiaKs9FS1y1L8sqYUD4FqCBz60U9ffsL2d/K0XJ/qGCxuPPcVUkoo8Qkmmyos6Gw4JCGHoY1AGQboXhDQX3PyVPNmG+S38BJ55bd1M0rJAuz68nIDkkX91/yuN30VV7QewSGn2ltZ12SKnS7xuGkMr8q6zEuet7114eBL2lN79RTIgCdoYB/NBKtdkmeCD8Sx+VPBych1slepvGkUQIplIg32FXA0gozNitQ0xTwx+Crb1OK/9Z9ypN1wsXeplKiUv4KkBYPaKNXAOdLr/1KVGoP64EIxP0Cq4be1ZEua3ZhtVPmHIk43h4tXH+IfFangU60XqoRDQSTis="
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure:
    github_token:
      secure:
