language: php
php:
  - '7.2'

install: true
scripts: echo "no-tests"

notifications:
  email: false
  slack:
    rooms:
      secure: "O7gaiki4jX++eADjMM/REPHPfCpgbQvmkcGPETsrQw8Pj8xNnNLE4OzOeoxIsNoZjLRMGnRVp600UrnJlEE1SqJkgjevyzJnCz0fc5SM66S8W3vpdgJofR5jm5E0Kk5omfxGehp38iiM9FtECRTuKd3zP9sk0pK07b1ROCWFxkAxxoU+7d49fiFwKz7ikPEXvyT6FhbZaSK6sRqk1WR5jrOBupZQUBbOXfGDkba3/Vq87gWe4VP22/lgdh+tpA1hZ+QJW2+IETjXxwiQ05E39vNWJXyi6pRL4qusJR+mH0yqTBY9CDVmd0B4m45gNo9FzaXMkxmdorIf7ypJw/WAe7NNQpL6QoiaKs9FS1y1L8sqYUD4FqCBz60U9ffsL2d/K0XJ/qGCxuPPcVUkoo8Qkmmyos6Gw4JCGHoY1AGQboXhDQX3PyVPNmG+S38BJ55bd1M0rJAuz68nIDkkX91/yuN30VV7QewSGn2ltZ12SKnS7xuGkMr8q6zEuet7114eBL2lN79RTIgCdoYB/NBKtdkmeCD8Sx+VPBych1slepvGkUQIplIg32FXA0gozNitQ0xTwx+Crb1OK/9Z9ypN1wsXeplKiUv4KkBYPaKNXAOdLr/1KVGoP64EIxP0Cq4be1ZEua3ZhtVPmHIk43h4tXH+IfFangU60XqoRDQSTis="
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "CHe5qWAqTB0zOp/ux9Ipc73v54HbHVdj/PSPK5mCSb5gmjSnacoyNfqSZ4jzBi9PoQdwGCXZCIIg0OL0cpemsyKPblmLVh64l2uYa2S9H07i0X0dL13mzHrXXYFRO4/sOoaB+LEJFIwdhFBzhHMWQXbyJChDungv3fvgxtttUI39JHCe86aAkky/uRGzMDP998OLA8ezYCe8iqAKtniyS42oGLg/Te+AHNsW+PCf439mfyCvblaAAgHujs9mxjJLsmDYELC3Gw3OvjVR8qf/1JteDMT5uNBSDJYYDjVsA7i/CfGgNTrPzydUFaq3z9SMJrCz1zMoEisqQKJsfSMFG0/APxx1/g8f1rEQEmdCRGs/9CE3vu8OXiI/aLFi8i2LRIcx19iA5yjibibEAwp+BpLQAS6EEbsjq9wrBmznRfSB4Qbr6UOzgOivhfAMRoHUHCHs9Zpe/otbC5oF+YbgkXaLq0Vt/CdUiKHT1ANrrRs2Gy+rAOsWqGcS/Rzu2Vy/P4Xn8RoAJT6KwMkQvcbE6sK2WRqPldCEEif+mny92keJmGi2ZrrmXpIWfB7/YAAQ20x8yaJqSLBzrK0AB62k77Qb+jDtg3lotNPFBhpbUouSQEJuwyKsBSuFp1hemo1yDBVDmWCctUWPu+rSB1Ql6F8Gs7duqLvC4pkLWKaFl0Q="
