# Project language
language: python

# Python version
python:
  - 2.7

# Allows use container-based infrastructure
sudo: false

# Cache pip dependencies
cache: pip

# Install python dependencies
install:
  - pip install -r requirements.txt
  - pip install mock mongomock

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export ADUSER_ROOT=/
  - cp .env.dist .env
  - git clone https://github.com/char0n/pybrowscap.git $PYTHONPATH/pybrowscap

stages:
  - test
  - quality

jobs:
  include:
    # Python unit tests
    - stage: test
      script: trial tests
    # Coverage generation and Sonar Qube
    - stage: quality
      script:
       - pip install coverage
       - coverage run `which trial` tests
       - coverage xml -i
       - sonar-scanner

# After a build, send email notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure:
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure:
    github_token:
      secure:
