sudo: required

language: jvm

jdk: openjdk9

services:
  - docker

env:
  global:
    - >-
      DOCKER_IMAGE=awlodarkiewicz/devops:build-latest
      HOST_PATH=/home/travis/build/adshares/aduser
      BUILD_PATH=/build/aduser
      BUILD_NAME=aduser_build
      PYTHONPATH=$PYTHONPATH:$BUILD_PATH
      ADUSER_TRACKING_SECRET=NotVerySecret_Proxy
      ADUSER_COOKIE_NAME=aduser_proxy_tid
      ADUSER_EXPIRY_PERIOD=4w
      ADUSER_MONGO_DB_PORT=27017
      ADUSER_MONGO_DB_NAME=aduser_cache
      ADUSER_LOG_CONFIG_FILE=$BUILD_PATH/config/log_config.json
      ADUSER_PLUGINS_PATH=$BUILD_PATH/aduser/plugins
      ADUSER_DATA_PATH=$BUILD_PATH/aduser/data
      ADUSER_PORT=9000
      ADUSER_DATA_PROVIDER=example

  matrix:
    - ADUSER_APP_ENV=dev

stages:
  - test
  - quality

before_script:
  # Enable aliases for non-interactive shells
  - shopt -s expand_aliases
  # Set alias - please note the missing quote you need to append.
  - alias in_docker='docker exec $BUILD_NAME /bin/bash -c "cd $BUILD_PATH && '
  # Set alias for cleanup
  - alias cleanup_docker='docker stop $BUILD_NAME && docker rm $BUILD_NAME'

jobs:
  include:
    # Python unit tests
    - stage: test
      script:
        ## Setup test environment
        # Run docker container
        - docker pull $DOCKER_IMAGE
        - env | grep ADUSER > aduser.env
        - >
          docker run -d
          --mount type=bind,src=$HOST_PATH,dst=$BUILD_PATH
          -e TRAVIS=true
          -e PYTHONPATH=$BUILD_PATH
          --env-file aduser.env
          --name $BUILD_NAME
          $DOCKER_IMAGE
          sleep infinity

        # Run pre-build script
        - in_docker /bin/bash scripts/pre-build.sh"

        # Run build script
        - in_docker /bin/bash scripts/build.sh"

        - in_docker pipenv run trial tests"

        # Cleanup
        - cleanup_docker

    # Coverage generation and Sonar Qube
    - stage: quality
      script:
        ## Setup test environment
        # Run docker container
        - docker pull $DOCKER_IMAGE
        - env | grep ADUSER > aduser.env
        - >
          docker run -d
          --mount type=bind,src=$HOST_PATH,dst=$BUILD_PATH
          -e TRAVIS=true
          -e PYTHONPATH=$BUILD_PATH
          --env-file aduser.env
          --name $BUILD_NAME
          $DOCKER_IMAGE
          sleep infinity

        # Run pre-build script
        - in_docker ./scripts/pre-build.sh"

        # Run build script
        - in_docker ./scripts/build.sh"

        - in_docker ./scripts/quality-test.sh"

        - sonar-scanner

        # Cleanup
        - cleanup_docker


# After a build, send email notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure:
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure:
    github_token:
      secure: