index:
    path: /
    controller: Adshares\Aduser\Controller\AppController::index
    methods: GET

info:
    path: /info.{_format}
    controller: Adshares\Aduser\Controller\AppController::info
    methods: GET
    defaults:
        _format: 'json'
    requirements:
        _format:  'json|txt|html'

privacy:
    path: /info/privacy.html
    controller: Adshares\Aduser\Controller\AppController::privacy
    methods: GET

# security
security_login:
    path: /login
    controller: Adshares\Aduser\Controller\SecurityController::login

security_logout:
    path: /logout

# panel
panel:
    path: /panel.html
    controller: Adshares\Aduser\Controller\PanelController::index
    methods: GET|POST

panel_patch:
    path: /panel/{id}
    controller: Adshares\Aduser\Controller\PanelController::patch
    methods: PATCH|OPTIONS
    requirements:
        id:  '[0-9]+'

# pixel
pixel_register:
    path: /{slug}/{adserver}/{tracking}/{nonce}.{_format}
    controller: Adshares\Aduser\Controller\PixelController::register
    methods: GET
    defaults:
        _format: 'html'
    requirements:
        slug:  '[a-zA-Z0-9_:.-]{8}'
        adserver:  '[a-zA-Z0-9_:.-]+'
        user:  '[a-zA-Z0-9_:.-]+'
        nonce: '[a-zA-Z0-9_:.-]+'
        _format:  'html|htm'

pixel_recaptcha:
    path: /re/{tracking}/{nonce}.html
    controller: Adshares\Aduser\Controller\PixelController::recaptchaRegister
    methods: GET|POST
    requirements:
        tracking:  '[0-9a-f]+'
        nonce: '[0-9a-f]+'

# API
taxonomy:
    path: /api/v{version}/taxonomy
    controller: Adshares\Aduser\Controller\DataController::taxonomy
    methods: GET
    requirements:
        version:  '1'

data:
    path: /api/v{version}/data/{adserver}/{tracking}
    controller: Adshares\Aduser\Controller\DataController::data
    methods: GET|POST|OPTIONS
    requirements:
        version:  '1'
        adserver:  '[a-zA-Z0-9_:.-]+'
        tracking:  '[a-zA-Z0-9_:.-]+'

data_batch:
    path: /api/v{version}/data/{adserver}
    controller: Adshares\Aduser\Controller\DataController::batch
    methods: POST
    requirements:
        version:  '1'
        adserver:  '[a-zA-Z0-9_:.-]+'


domain:
    path: /api/v{version}/domain/{domain}
    controller: Adshares\Aduser\Controller\DataController::domain
    methods: GET|OPTIONS
    requirements:
        version:  '1'